version: '3.9'
services:
  airport-db:
    image: library/postgres:latest
    ports:
      - "5432:5432"
    container_name: choice-tales-postgres
    environment:
      - POSTGRES_DB= choice-tales
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
    volumes:
      - ./data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql