micronaut:
  application:
    name: complete

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/choice-tales
    driverClassName: org.postgresql.Driver
    username: 'docker'
    password: 'docker'

jpa:
  default:
    entity-scan:
      packages: 'example.micronaut.data'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true